### ISSUE TITLE
Investigate flacky cypress tests on Linux

### ISSUE THREAD

**Issue by warpdesign** [warpdesign/react-explorer#178]
> 1) filetable rename feature renaming should be cancelled if rename input field gets blur event while active:
     CypressError: cy.focus() can only be called on a valid focusable element. Your subject is a: <span title="folder2" class="file-label">folder2</span>
      at Object.cypressErr (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:104836:11)
      at Object.throwErr (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:104791:18)
      at Object.throwErrByPath (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:104823:17)
      at Context.focus (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:86501:16)
      at Context.<anonymous> (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:100503:21)
      at http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:100025:33
      at tryCatcher (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:138863:23)
      at Promise._settlePromiseFromHandler (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:136799:31)
      at Promise._settlePromise (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:136856:18)
      at Promise._settlePromiseCtx (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:136893:10)
      at Async../node_modules/bluebird/js/release/async.js.Async._drainQueue (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:133593:12)
      at Async../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:133598:10)
      at Async.drainQueues (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:133472:14)

See: https://cypress.io/blog/2020/10/20/introducing-flaky-test-detection-alerts/

**Comment by warpdesign** [comment]
This doesn't seem to fail anymore: closing.
