### ISSUE TITLE
FTP: unexpected socket time out reached

### ISSUE THREAD

**Issue by warpdesign** [warpdesign/react-explorer#22]
Sometimes the following error appears:

> Error: Client is closed
at Promise (file:///Users/leo/dev/react-ftp/dist/gui.js:29145:29)
at new Promise (<anonymous>)
at FTPContext.handle (file:///Users/leo/dev/react-ftp/dist/gui.js:29125:16)
at Client.connect (file:///Users/leo/dev/react-ftp/dist/gui.js:28132:25)
at Client.access (file:///Users/leo/dev/react-ftp/dist/gui.js:28229:36)
at Client../src/services/plugins/FsSimpleFtp.ts.Client.login (file:///Users/leo/dev/react-ftp/dist/gui.js:100981:31)
at SimpleFtpApi.<anonymous> (file:///Users/leo/dev/react-ftp/dist/gui.js:101085:55)
at step (file:///Users/leo/dev/react-ftp/dist/gui.js:100927:23)
at Object.next (file:///Users/leo/dev/react-ftp/dist/gui.js:100908:53)
at file:///Users/leo/dev/react-ftp/dist/gui.js:100902:71
Closing reason: Error: Timeout (control socket)
at Socket.socket.once (file:///Users/leo/dev/react-ftp/dist/gui.js:29214:58)
at Object.onceWrapper (events.js:273:13)
at Socket.emit (events.js:182:13)
at Socket._onTimeout (net.js:445:8)
at ontimeout (timers.js:427:11)
at tryOnTimeout (timers.js:289:5)
at listOnTimeout (timers.js:252:5)
at Timer.processTimers (timers.js:212:10)

For example when stopping into a debugger.

A bug has been opened in [basic-ftp](https://github.com/electron/electron/issues/14915) but it seems to be related to Electron/node.js instead: https://github.com/electron/electron/issues/14915

**Comment by warpdesign** [comment]
Same problem happens when initiating a transfer that's longer than the default (30sec) timeout.

**Comment by warpdesign** [comment]
Closing: will reopen once ftp plugin is developed.
